import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Figtree } from "next/font/google";
import "./globals.css";

const figTree = Figtree({
  subsets: ["latin"],
  weight: "400",
  variable: "--figtree",
});

export const metadata: Metadata = {
  title: "Higher or Lower: Spotify Edition",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={figTree.variable}>
      <body>{children}</body>
    </html>
  );
}
