name: Unit Test
run-name: Unit Test
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Unit-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Unit test automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
      - run: echo "🍏 This job's status is ${{ job.status }}."